function [A] = heat_contribution(M, Elem, e, Q, dx, u)
% function for evaluating the heat generated by the electric problem
% --- INPUT  ---
% M    : x,y coordinates of the points
% Elem : global matrix of the boundary elements
% f    : global number of the boundary element considered
% dx   : x displacement
% u    : Gauss nodes
% --- OUTPUT ---
% A : Term for the updating

A = zeros(4,1);
r = M(Elem(e,1),1);

for i = 1:4
    sum = 0;
    for xi_coord = 1:4
        [Alpha, dalpha_xi, dalpha_eta] = alpha(u(xi_coord),u(xi_coord));
        % summation over the gauss nodes
        w1 = u(xi_coord);
        sum = sum+(Alpha(i))*(r+dx/2+u(xi_coord)*dx)*w1;
    end
    A(i) = Q*sum;
end

end
